backend/models.py
import psycopg2
from db import get_db_connection

def create_tables():
    conn = get_db_connection()
    cur = conn.cursor()
    
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            username VARCHAR(50) UNIQUE NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL
        );
    """)

    cur.execute("""
        CREATE TABLE IF NOT EXISTS auth (
            id SERIAL PRIMARY KEY,
            user_id INT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );
    """)

    conn.commit()
    cur.close()
    conn.close()
    print("Tablas creadas correctamente.")

if __name__ == "__main__":
    create_tables()

backend/__init__.py
import os
from flask import Flask
from .config import Config 
from .routes.login import login, index
from .routes.homepage import homepage
from .routes.register import register
from .routes.logout import logout


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.secret_key = os.environ.get('SECRET_KEY')
    app.register_blueprint(login)
    app.register_blueprint(homepage)
    app.register_blueprint(register)
    app.register_blueprint(logout)
    app.register_blueprint(index)


    return app

backend/routes/homepage.py
from flask import Blueprint, render_template, session
from backend.utils.auth import login_required

homepage = Blueprint('homepage', __name__)

@homepage.route('/home')
@login_required
def home():
    return render_template('homepage.html', user=session.get('user'))

backend/routes/login.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from backend.db import get_db_connection
from werkzeug.security import check_password_hash

login= Blueprint('login', __name__)
index = Blueprint('index', __name__)

@index.route('/', methods=['GET', 'POST'])
def index_view():
    return render_template('index.html')


@login.route('/login', methods=['GET', 'POST'])
def login_view():
    if request.method == 'POST':
        user = request.form['user']
        password = request.form['password']
        
        conn = get_db_connection()
        cur = conn.cursor()
        cur.execute("""
        SELECT u.id, u.username, u.email, a.password
        FROM users u
        JOIN auth a ON u.id = a.user_id
        WHERE u.username = %s
        """, (user,))
        user_data = cur.fetchone()
        cur.close()
        conn.close()
        
        if user_data and check_password_hash(user_data[3], password):
            session['user_id'] = user_data[0]
            session['username'] = user_data[1]
            return redirect(url_for('homepage.home'))
        else:
            flash('Credenciales incorrectas')
    return render_template('login.html')

backend/routes/logout.py
from flask import Blueprint, redirect, url_for, session, flash

logout = Blueprint('logout', __name__)

@logout.route('/logout')
def logout_view():
    session.pop('user_id', None)  # Eliminar 'user_id' de la sesion
    flash('Has cerrado sesión')
    return redirect(url_for('login.login_view'))

backend/routes/register.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from werkzeug.security import generate_password_hash
from backend.db import get_db_connection
from time import sleep

register = Blueprint('register', __name__)

@register.route('/register', methods=['GET', 'POST'])
def register_view():
    if request.method == 'POST':
        #crear variables y almacenar lo que se agrega en el campo de registro del archivo html
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        hash_pass = generate_password_hash(password, method='pbkdf2:sha256')
        #conectar con pg
        conn = get_db_connection()
        cur = conn.cursor()
        #insertar los datos
        try:
            cur.execute("""
            INSERT INTO users (username, email) VALUES (%s, %s) RETURNING id
            """, (username, email))
            user_id = cur.fetchone()[0]

            cur.execute("""
            INSERT INTO auth (user_id, password) VALUES (%s, %s)
            """, (user_id, hash_pass))
            conn.commit()
            cur.close()
            conn.close()
            flash(f'usuario registrado, intenta iniciar sesion')
            return redirect(url_for('login.login_view'))
        except Exception as e:
            conn.rollback()
            cur.close()
            conn.close()
            flash(f'Error al registrar, intenta de nuevo: {str(e)}')
    return render_template('register.html')
	

backend/utils/auth.py
from functools import wraps
from flask import session, redirect, url_for, flash


def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            flash("Debes iniciar sesión para acceder a esta página.")
            return redirect(url_for('login.login_view'))
        return f(*args, **kwargs)
    return decorated_function

backend/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
    <title>Inicio</title>
</head>
<body>
    <h1>Bienvenido</h1>
    <p>Has iniciado sesión correctamente.</p>
    <a href="{{ url_for('logout.logout_view') }}">
	    <button>Cerrar sesion</button>
    </a>
</body>
</html>

backend/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h2>Login</h2>
    <a href="{{ url_for('login.login_view') }}">
        <button>Iniciar sesion</button>
    </a>
</body>
</html>

backend/templates/login.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h2>Iniciar Sesión</h2>
    <form action="{{ url_for('login.login_view') }}" method="post">
        <label for="user">Usuario:</label>
        <input type="text" id="user" name="user" required><br><br>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required><br><br>
             {% with messages = get_flashed_messages() %}
       {% if messages %}
          <ul>
             {% for message in messages %}
                <li style="color: red;">{{ message }}</li>
             {% endfor %}
          </ul>
       {% endif %}
    {% endwith %}
        <button type="submit">Login</button>
    </form>
        <a href= "{{ url_for('register.register_view') }}">
                <button>Registrarme</button>
        </a>
</body>
</html>

backend/templates/register.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registro de Usuario</title>
</head>
<body>
    <h2>Registrar Nuevo Usuario</h2>
    <form action="{{ url_for('register.register_view') }}" method="post">
        <label for="username">Nombre de Usuario:</label>
        <input type="text" id="username" name="username" required><br><br>

        <label for="email">Correo Electrónico:</label>
        <input type="email" id="email" name="email" required><br><br>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required><br><br>

        <button type="submit">Registrar</button>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      	<ul>
            {% for message in messages %}
            	<li style="color: red;">{{ message }}</li>
            {% endfor %}
        </ul>
      {% endif %}
      {% endwith %}
    </form>

    <br><br>
    <a href="{{ url_for('login.login_view') }}">¿Ya tienes una cuenta? Inicia sesión aquí.</a>
</body>
</html>